export const FETCH_REPOSITORIES = "FETCH_REPOSITORIES";
export const FETCH_REPOSITORIES_SUCCESS = "FETCH_REPOSITORIES_SUCCESS";
export const FETCH_REPOSITORIES_FAIL = "FETCH_REPOSITORIES_FAIL"

export const FETCH_PULL_REQUESTS = "FETCH_PULL_REQUESTS";
export const FETCH_PULL_REQUESTS_SUCCESS = "FETCH_PULL_REQUESTS_SUCCESS";
export const FETCH_PULL_REQUESTS_FAIL = "FETCH_PULL_REQUESTS_FAIL";